# Generated by Django 3.2.9 on 2021-11-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
